---

- name: Installation tasks
  tags:
    - auditd_install
    - auditd
  become: true
  block:
  - name: Install auditd package
    when: ansible_os_family == 'Debian'
    ansible.builtin.apt:
      name: ["{{ item }}"]
      update_cache: true
      state: "{{ auditd_package_ensure }}" 
    with_items: "{{ auditd_package_name }}"
  - name: Install auditd package
    when: ansible_os_family == 'RedHat'
    ansible.builtin.yum:
      name: ["{{ item }}"]
      state: "{{ auditd_package_ensure }}" 
    with_items: "{{ auditd_package_name }}"
